server:
  port: 8180
  error:
    include-message: always # Выводить сообщение в отловленной ошибке

application:
  reader:
    max-allowed-books: 3 # настойка максимальное количество книг выданных читателю

spring:
  datasource:
    url: jdbc:h2:mem:homework
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: issuance-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    status-page-url-path: ${spring.cloud.client.hostname}